services:
  postgres:
    image: postgres
    container_name: postgres_MarketPlace
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: MarketPlace_db  
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - MarketPlace_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_MarketPlace
    environment:
      PGADMIN_DEFAULT_EMAIL: sajjadmokhtari386@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - MarketPlace_network
    restart: unless-stopped
    depends_on:
      - postgres